data:
  replicaCount: 4
  service:
    # FIXME the nginx.conf should probably be configurable here instead.
    name: data
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      add:
      - NET_BIND_SERVICE
      drop:
      - ALL
    privileged: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 92188

backend:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      add:
      - NET_BIND_SERVICE
      drop:
      - ALL
    privileged: false
    readOnlyRootFilesystem: false
    runAsNonRoot: false

frontend:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      add:
      - CHOWN
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
      - SETGID
      - SETUID
      drop:
      - ALL
    privileged: false
    readOnlyRootFilesystem: false
    runAsNonRoot: false
  service:
    type: NodePort

redis:
    enabled: false
