apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nmdc.fullname" . }}-backend
  labels:
    {{- include "nmdc.labels" . | nindent 4 }}
    component: backend
  {{- with .Values.backend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  POSTGRES_URI: {{ printf "postgresql://%s-postgresql%24%s@%s-postgresql:5432/%s" ( include "nmdc.fullname" . ) .Values.global.postgresql.auth.password ( include "nmdc.fullname" . ) .Values.global.postgresql.auth.database | b64enc }}
  PGPASSWORD: {{ .Values.global.postgresql.auth.password | b64enc }}
