apiVersion: v1
kind: Service
metadata:
  name: {{ include "nmdc.fullname" . }}-backend
  labels:
    {{- include "nmdc.labels" . | nindent 4 }}
    component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nmdc.selectorLabels" . | nindent 4 }}
    component: backend
