apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nmdc.fullname" . }}-backend
  labels:
    {{- include "nmdc.labels" . | nindent 4 }}
    component: backend
  {{- with .Values.backend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  POSTGRES_URI: {{ printf "postgresql://%s:%s@%s-postgresql:5432/%s" .Values.global.postgresql.auth.username .Values.global.postgresql.auth.password ( include "nmdc.fullname" . ) .Values.global.postgresql.auth.database | b64enc }}
  ADMIN_POSTGRES_URI: {{ printf "postgresql://%s:%s@%s-postgresql:5432/%s" "postgres" .Values.global.postgresql.auth.postgresPassword ( include "nmdc.fullname" . ) .Values.global.postgresql.auth.database | b64enc }}
  PGPASSWORD: {{ .Values.global.postgresql.auth.password | b64enc }}
  {{- if .Values.backend.oidc.enabled }}
  CLIENT_ID: {{ .Values.backend.oidc.client.id | b64enc }}
  CLIENT_SECRET: {{ .Values.backend.oidc.client.secret | b64enc }}
  {{- end }}
