{{- if .Values.data.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nmdc.data.serviceAccountName" . }}
  labels:
    {{- include "nmdc.labels" . | nindent 4 }}
    component: data
  {{- with .Values.data.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
