apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nmdc.fullname" . }}-frontend
  labels:
    {{- include "nmdc.labels" . | nindent 4 }}
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "nmdc.selectorLabels" . | nindent 6 }}
      component: frontend
  template:
    metadata:
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nmdc.selectorLabels" . | nindent 8 }}
        component: frontend
    spec:
      {{- with .Values.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nmdc.frontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          env:
          - name: BACKEND_URL
            value: http://{{ include "nmdc.fullname" . }}-backend.{{ .Release.Namespace }}.svc.cluster.local:8000
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
# FIXME
#         livenessProbe:
#           httpGet:
#             path: /
#             port: http
#         readinessProbe:
#           httpGet:
#             path: /
#             port: http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
