apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{- if .Values.global.spin.enabled }}
    field.cattle.io/creatorId: "{{ .Values.global.spin.creatorId }}"
    {{- end }}
  labels:
    {{- if .Values.global.spin.enabled }}
    workload.user.cattle.io/workloadselector: {{ .Values.global.spin.workloadSelector }}
    {{- end }}
  name: {{ include "nmdc-test.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- if .Values.global.spin.enabled }}
      workload.user.cattle.io/workloadselector: {{ .Values.global.spin.workloadSelector }}
      {{- end }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- if .Values.global.spin.enabled }}
        workload.user.cattle.io/workloadselector: {{ .Values.global.spin.workloadSelector }}
        {{- end }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ include "nmdc-test.fullname" . }}
        resources: {}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      terminationGracePeriodSeconds: 30

